# Site settings
title: "Healthy Desires"
email: 
description: > # 
keywords: ""
excerpt_separator: <!--more-->
permalink: /blog/:categories/:title.html
baseurl: ""


# URL Settings
#   DEVELOPMENT
url: "http://dev.healthydesires.com.au/"
images_url: "/images/"
assets_url: ""
#   PRODUCTION
# url: "http://.com.au"
# images_url: "//images.cdn..com.au/"
# assets_url: "//styles.cdn..com.au/"


#Business Settings
founder:
  firstName: "Raya"
  lastName: "Rantall"
  link: "http://healthydesires.com.au"
business:
  state: "VIC"
  postCode: "3280"
  city: "Warrnambool"
  address: "3 Pappas Drive"
  internationalNumber: ""
  localNumber: ""
  logo: "images/healthy-desires-logo.png"
social:
  facebook: ""
  googlePlus: ""
  twitter: ""
  linkedIn: ""
  pintrest: ""


# Build settings
markdown: kramdown
sass:
  style: compressed
timezone: "Australia/Melbourne"
sitemap:
    exclude:
        - "/style.css"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
optimiser:
  enabled: false